language: java
jdk:
  - oraclejdk8
services:
  - postgresql
sudo: required
cache:
  directories:
    - $HOME/.m2
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)